In [1]:
#Tacotron Encoder
#1. PyTorch Tutorial 부터 해보자.

In [27]:
import torch

x = torch.empty(5,3)
x = torch.rand(5,3)
x = torch.zeros(5,3, dtype=torch.double)
x = torch.tensor([1,1]) #data 바로생성
x = x.new_ones(5,3, dtype = torch.double)
x = torch.randn_like(x, dtype=torch.double)
#print(x)
#print(x.size())

#덧셈시 x + y || torch.add(x,y)
y = torch.rand(5,3, dtype = torch.double)
y.add_(x)
print(y)

tensor([[ 0.7871,  2.2240, -1.2639],
        [ 0.6231,  1.0924,  0.7823],
        [ 0.7165, -0.7567,  1.8064],
        [-0.7446,  0.7466,  0.7452],
        [ 0.0978,  1.3803, -0.9749]], dtype=torch.float64)


In [31]:

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(y.size())

torch.Size([16])


In [47]:
#Autograd
x = torch.ones(2,2, requires_grad = True)
print(x)
y = x+ 2
print(y)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [50]:
x= torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)
gradients = torch.tensor([])

In [71]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6, 16,5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84,10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x= F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:] #all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)
params = list(net.parameters())
print(params[0].size())
input = torch.randn(1,1,32,32)
output = net(input)
target = torch.arange(1.0,11)
print(target)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
net.zero_grad()

print(net.conv1.bias.grad)
loss.backward()
print(net.conv1.bias.grad)

learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)
    
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr = 0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
torch.Size([6, 1, 5, 5])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
None
tensor([ 0.0338, -0.0496, -0.0474,  0.0025, -0.0098, -0.0181])


In [11]:
import torch
x = torch.randn(2, 7)


In [12]:

print(torch.cat([x,x], -1))

tensor([[ 1.8581,  0.7425, -0.0360, -0.2515,  0.5209,  0.7518,  1.2259,  1.8581,
          0.7425, -0.0360, -0.2515,  0.5209,  0.7518,  1.2259],
        [ 1.3082,  0.0330, -0.2029, -1.7769, -0.1918, -0.4781, -3.0698,  1.3082,
          0.0330, -0.2029, -1.7769, -0.1918, -0.4781, -3.0698]])
